networks:
  app-network:
    driver: bridge

services:
  app:
    image: emarf/nodejs2024q3-service-app:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: emarf-nest-api
    restart: always
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.json:/app/tsconfig.build.json
      - ./doc/api.yaml:/app/doc/api.yaml

  postgres:
    image: emarf/nodejs2024q3-service-postgres:latest
    # build:
    #   context: ./prisma
    #   dockerfile: Dockerfile
    container_name: emarf-postgres-db
    restart: always
    ports:
      - '${PORT_DB}:${PORT_DB}'
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
